{ pkgs }:

let
  androidComposition = pkgs.androidenv.composeAndroidPackages {
    platformVersions = [ "31" "35" "36" ];
    buildToolsVersions = [ "31.0.0" "35.0.0" "36.0.0" ];
    includeEmulator = true;
    includeSystemImages = true;
    systemImageTypes = [ "google_apis" ];
    abiVersions = [ "x86_64" ];
    includeNDK = true;
    ndkVersions = [ "27.1.12297006" "27.0.12077973" ];
    cmakeVersions = [ "3.22.1" ];
  };
in
rec {
  androidSdk = androidComposition.androidsdk;
  jdk = pkgs.jdk17;
  extraPackages = [ pkgs.nix-ld ];

  nixLdHook = ''
    export NIX_LD=$(nix eval --raw nixpkgs#stdenv.cc.bintools.dynamicLinker)
    export NIX_LD_LIBRARY_PATH="${pkgs.lib.makeLibraryPath [
      pkgs.stdenv.cc.cc
      pkgs.gcc.cc.lib
      pkgs.glibc
      pkgs.zlib
      pkgs.icu
      pkgs.openssl
      pkgs.libcxx
      pkgs.libxcb
      pkgs.xorg.libX11
    ]}"
  '';
  
  shellHook = ''
    # Java & Android SDK setup for React Native / Expo Android
    export JAVA_HOME="${pkgs.jdk17}"
    export PATH="$JAVA_HOME/bin:$PATH"
    
    # Set up composite Android SDK with required components
    export ANDROID_SDK_ROOT="$HOME/.android/nix-sdk"
    export ANDROID_HOME="$ANDROID_SDK_ROOT"
    mkdir -p "$ANDROID_SDK_ROOT"
    
    # Link SDK components from Nix store
    ln -sfn "${androidComposition.androidsdk}/libexec/android-sdk/emulator" "$ANDROID_SDK_ROOT/emulator"
    ln -sfn "${androidComposition.androidsdk}/libexec/android-sdk/system-images" "$ANDROID_SDK_ROOT/system-images"
    ln -sfn "${androidComposition.androidsdk}/libexec/android-sdk/platform-tools" "$ANDROID_SDK_ROOT/platform-tools"
    ln -sfn "${androidComposition.androidsdk}/libexec/android-sdk/build-tools" "$ANDROID_SDK_ROOT/build-tools"
    ln -sfn "${androidComposition.androidsdk}/libexec/android-sdk/platforms" "$ANDROID_SDK_ROOT/platforms"
    ln -sfn "${androidComposition.androidsdk}/libexec/android-sdk/ndk" "$ANDROID_SDK_ROOT/ndk"
    ln -sfn "${androidComposition.androidsdk}/libexec/android-sdk/cmake" "$ANDROID_SDK_ROOT/cmake"
    ln -sfn "${androidComposition.androidsdk}/libexec/android-sdk/licenses" "$ANDROID_SDK_ROOT/licenses"
    
    # Add Android tools to PATH
    export PATH="${androidComposition.androidsdk}/bin:$PATH"
    export PATH="$ANDROID_SDK_ROOT/platform-tools:$PATH"
    
    # Setup Android emulator device if it doesn't exist
    if [ ! -d "$HOME/.android/avd/Pixel_3a_API_31.avd" ]; then
      mkdir -p "$HOME/.android/avd/Pixel_3a_API_31.avd"
      
      # Create AVD config file
      cat > "$HOME/.android/avd/Pixel_3a_API_31.avd/config.ini" << 'AVDCONFIG'
avd.ini.encoding=UTF-8
AvdId=Pixel_3a_API_31
PlayStore.Enabled=false
abi.type=x86_64
hw.accelerometer=yes
hw.audioInput=yes
hw.audioOutput=yes
hw.battery=yes
hw.dPad=no
hw.device.manufacturer=Google
hw.device.name=pixel_3a
hw.gps=yes
hw.gpu.enabled=yes
hw.gpu.mode=host
hw.initialOrientation=Portrait
hw.keyboard=no
hw.lcd.density=440
hw.lcd.height=2220
hw.lcd.width=1080
hw.mainKeys=no
hw.ramDisk=ramdisk.img
hw.sensors.orientation=yes
hw.sensors.proximity=yes
image.sysdir.1=system-images/android-31/google_apis/x86_64/
showDeviceFrame=yes
hw.cpu.ncore=4
hw.cpu.arch=x86_64
AVDCONFIG
      
      # Create AVD registry entry
      cat > "$HOME/.android/avd/Pixel_3a_API_31.ini" << AVDINI
# This file was automatically generated by the Android SDK.
# Do not modify it; your changes will be overwritten.
# This file must *always* be encoded with UTF-8.
avd.ini.encoding=UTF-8
path=$HOME/.android/avd/Pixel_3a_API_31.avd
path.rel=avd/Pixel_3a_API_31.avd
target=android-31
AVDINI
      
      echo "✓ Created Android emulator device: Pixel_3a_API_31"
    fi

    export USE_ANDROID=1
    ${nixLdHook}
    
    echo "- Java $(java -version 2>&1 | head -n1)"
    command -v adb >/dev/null 2>&1 && echo "- adb $(adb version | head -n1)" || echo "- adb not found (install SDK packages)"
    command -v emulator >/dev/null 2>&1 && echo "- emulator $(emulator -version | head -n1)" || echo "- emulator not found"
  '';
}
