/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Yield.xyz API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type {
    ActionDto,
    ActionsControllerEnterYield400,
    ActionsControllerEnterYield401,
    ActionsControllerEnterYield403,
    ActionsControllerEnterYield429,
    ActionsControllerEnterYield500,
    ActionsControllerExitYield400,
    ActionsControllerExitYield401,
    ActionsControllerExitYield403,
    ActionsControllerExitYield429,
    ActionsControllerExitYield500,
    ActionsControllerGetAction400,
    ActionsControllerGetAction401,
    ActionsControllerGetAction429,
    ActionsControllerGetAction500,
    ActionsControllerGetActionPathParameters,
    ActionsControllerGetActions200,
    ActionsControllerGetActions400,
    ActionsControllerGetActions401,
    ActionsControllerGetActions429,
    ActionsControllerGetActions500,
    ActionsControllerGetActionsParams,
    ActionsControllerManageYield400,
    ActionsControllerManageYield401,
    ActionsControllerManageYield403,
    ActionsControllerManageYield429,
    ActionsControllerManageYield500,
    CreateActionDto,
    CreateManageActionDto,
    SubmitHashDto,
    SubmitTransactionDto,
    TransactionDto,
    TransactionsControllerGetTransaction400,
    TransactionsControllerGetTransaction401,
    TransactionsControllerGetTransaction429,
    TransactionsControllerGetTransaction500,
    TransactionsControllerGetTransactionPathParameters,
    TransactionsControllerSubmitTransaction401,
    TransactionsControllerSubmitTransaction429,
    TransactionsControllerSubmitTransaction500,
    TransactionsControllerSubmitTransactionHash401,
    TransactionsControllerSubmitTransactionHash429,
    TransactionsControllerSubmitTransactionHash500,
    TransactionsControllerSubmitTransactionHashPathParameters,
    TransactionsControllerSubmitTransactionPathParameters,
} from './index.schemas';
import { httpClient } from '../httpClient';

/**
 * Retrieve all actions performed by a user, with optional filtering by yield, status, category, etc. In the future, this may include personalized action recommendations.
 * @summary Get user actions
 */
export type ActionsControllerGetActionsResponse200 = {
    data: ActionsControllerGetActions200;
    status: 200;
};

export type ActionsControllerGetActionsResponse400 = {
    data: ActionsControllerGetActions400;
    status: 400;
};

export type ActionsControllerGetActionsResponse401 = {
    data: ActionsControllerGetActions401;
    status: 401;
};

export type ActionsControllerGetActionsResponse429 = {
    data: ActionsControllerGetActions429;
    status: 429;
};

export type ActionsControllerGetActionsResponse500 = {
    data: ActionsControllerGetActions500;
    status: 500;
};

export type ActionsControllerGetActionsResponseSuccess = ActionsControllerGetActionsResponse200 & {
    headers: Headers;
};
export type ActionsControllerGetActionsResponseError = (
    | ActionsControllerGetActionsResponse400
    | ActionsControllerGetActionsResponse401
    | ActionsControllerGetActionsResponse429
    | ActionsControllerGetActionsResponse500
) & {
    headers: Headers;
};

export type ActionsControllerGetActionsResponse =
    | ActionsControllerGetActionsResponseSuccess
    | ActionsControllerGetActionsResponseError;

export const getActionsControllerGetActionsUrl = (params: ActionsControllerGetActionsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/v1/actions?${stringifiedParams}` : `/v1/actions`;
};

export const actionsControllerGetActions = (
    params: ActionsControllerGetActionsParams,
    options?: RequestInit,
): Promise<ActionsControllerGetActionsResponse> =>
    httpClient<ActionsControllerGetActionsResponse>(getActionsControllerGetActionsUrl(params), {
        ...options,
        method: 'GET',
    });

/**
 * Retrieve detailed information about a specific action including current status, transactions, and execution details.
 * @summary Get action details
 */
export type ActionsControllerGetActionResponse200 = {
    data: ActionDto;
    status: 200;
};

export type ActionsControllerGetActionResponse400 = {
    data: ActionsControllerGetAction400;
    status: 400;
};

export type ActionsControllerGetActionResponse401 = {
    data: ActionsControllerGetAction401;
    status: 401;
};

export type ActionsControllerGetActionResponse404 = {
    data: void;
    status: 404;
};

export type ActionsControllerGetActionResponse429 = {
    data: ActionsControllerGetAction429;
    status: 429;
};

export type ActionsControllerGetActionResponse500 = {
    data: ActionsControllerGetAction500;
    status: 500;
};

export type ActionsControllerGetActionResponseSuccess = ActionsControllerGetActionResponse200 & {
    headers: Headers;
};
export type ActionsControllerGetActionResponseError = (
    | ActionsControllerGetActionResponse400
    | ActionsControllerGetActionResponse401
    | ActionsControllerGetActionResponse404
    | ActionsControllerGetActionResponse429
    | ActionsControllerGetActionResponse500
) & {
    headers: Headers;
};

export type ActionsControllerGetActionResponse =
    | ActionsControllerGetActionResponseSuccess
    | ActionsControllerGetActionResponseError;

export const getActionsControllerGetActionUrl = ({
    actionId,
}: ActionsControllerGetActionPathParameters) => `/v1/actions/${actionId}`;

export const actionsControllerGetAction = (
    { actionId }: ActionsControllerGetActionPathParameters,
    options?: RequestInit,
): Promise<ActionsControllerGetActionResponse> =>
    httpClient<ActionsControllerGetActionResponse>(getActionsControllerGetActionUrl({ actionId }), {
        ...options,
        method: 'GET',
    });

/**
 * Generate the transactions needed to enter a yield position with the provided parameters.
 * @summary Enter a yield
 */
export type ActionsControllerEnterYieldResponse201 = {
    data: ActionDto;
    status: 201;
};

export type ActionsControllerEnterYieldResponse400 = {
    data: ActionsControllerEnterYield400;
    status: 400;
};

export type ActionsControllerEnterYieldResponse401 = {
    data: ActionsControllerEnterYield401;
    status: 401;
};

export type ActionsControllerEnterYieldResponse403 = {
    data: ActionsControllerEnterYield403;
    status: 403;
};

export type ActionsControllerEnterYieldResponse404 = {
    data: void;
    status: 404;
};

export type ActionsControllerEnterYieldResponse429 = {
    data: ActionsControllerEnterYield429;
    status: 429;
};

export type ActionsControllerEnterYieldResponse500 = {
    data: ActionsControllerEnterYield500;
    status: 500;
};

export type ActionsControllerEnterYieldResponseSuccess = ActionsControllerEnterYieldResponse201 & {
    headers: Headers;
};
export type ActionsControllerEnterYieldResponseError = (
    | ActionsControllerEnterYieldResponse400
    | ActionsControllerEnterYieldResponse401
    | ActionsControllerEnterYieldResponse403
    | ActionsControllerEnterYieldResponse404
    | ActionsControllerEnterYieldResponse429
    | ActionsControllerEnterYieldResponse500
) & {
    headers: Headers;
};

export type ActionsControllerEnterYieldResponse =
    | ActionsControllerEnterYieldResponseSuccess
    | ActionsControllerEnterYieldResponseError;

export const getActionsControllerEnterYieldUrl = () => `/v1/actions/enter`;

export const actionsControllerEnterYield = (
    createActionDto: CreateActionDto,
    options?: RequestInit,
): Promise<ActionsControllerEnterYieldResponse> =>
    httpClient<ActionsControllerEnterYieldResponse>(getActionsControllerEnterYieldUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(createActionDto),
    });

/**
 * Generate the transactions needed to exit a yield position with the provided parameters.
 * @summary Exit a yield
 */
export type ActionsControllerExitYieldResponse201 = {
    data: ActionDto;
    status: 201;
};

export type ActionsControllerExitYieldResponse400 = {
    data: ActionsControllerExitYield400;
    status: 400;
};

export type ActionsControllerExitYieldResponse401 = {
    data: ActionsControllerExitYield401;
    status: 401;
};

export type ActionsControllerExitYieldResponse403 = {
    data: ActionsControllerExitYield403;
    status: 403;
};

export type ActionsControllerExitYieldResponse404 = {
    data: void;
    status: 404;
};

export type ActionsControllerExitYieldResponse429 = {
    data: ActionsControllerExitYield429;
    status: 429;
};

export type ActionsControllerExitYieldResponse500 = {
    data: ActionsControllerExitYield500;
    status: 500;
};

export type ActionsControllerExitYieldResponseSuccess = ActionsControllerExitYieldResponse201 & {
    headers: Headers;
};
export type ActionsControllerExitYieldResponseError = (
    | ActionsControllerExitYieldResponse400
    | ActionsControllerExitYieldResponse401
    | ActionsControllerExitYieldResponse403
    | ActionsControllerExitYieldResponse404
    | ActionsControllerExitYieldResponse429
    | ActionsControllerExitYieldResponse500
) & {
    headers: Headers;
};

export type ActionsControllerExitYieldResponse =
    | ActionsControllerExitYieldResponseSuccess
    | ActionsControllerExitYieldResponseError;

export const getActionsControllerExitYieldUrl = () => `/v1/actions/exit`;

export const actionsControllerExitYield = (
    createActionDto: CreateActionDto,
    options?: RequestInit,
): Promise<ActionsControllerExitYieldResponse> =>
    httpClient<ActionsControllerExitYieldResponse>(getActionsControllerExitYieldUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(createActionDto),
    });

/**
 * Generate the transactions needed to perform management actions on a yield position.
 * @summary Manage a yield
 */
export type ActionsControllerManageYieldResponse201 = {
    data: ActionDto;
    status: 201;
};

export type ActionsControllerManageYieldResponse400 = {
    data: ActionsControllerManageYield400;
    status: 400;
};

export type ActionsControllerManageYieldResponse401 = {
    data: ActionsControllerManageYield401;
    status: 401;
};

export type ActionsControllerManageYieldResponse403 = {
    data: ActionsControllerManageYield403;
    status: 403;
};

export type ActionsControllerManageYieldResponse404 = {
    data: void;
    status: 404;
};

export type ActionsControllerManageYieldResponse429 = {
    data: ActionsControllerManageYield429;
    status: 429;
};

export type ActionsControllerManageYieldResponse500 = {
    data: ActionsControllerManageYield500;
    status: 500;
};

export type ActionsControllerManageYieldResponseSuccess =
    ActionsControllerManageYieldResponse201 & {
        headers: Headers;
    };
export type ActionsControllerManageYieldResponseError = (
    | ActionsControllerManageYieldResponse400
    | ActionsControllerManageYieldResponse401
    | ActionsControllerManageYieldResponse403
    | ActionsControllerManageYieldResponse404
    | ActionsControllerManageYieldResponse429
    | ActionsControllerManageYieldResponse500
) & {
    headers: Headers;
};

export type ActionsControllerManageYieldResponse =
    | ActionsControllerManageYieldResponseSuccess
    | ActionsControllerManageYieldResponseError;

export const getActionsControllerManageYieldUrl = () => `/v1/actions/manage`;

export const actionsControllerManageYield = (
    createManageActionDto: CreateManageActionDto,
    options?: RequestInit,
): Promise<ActionsControllerManageYieldResponse> =>
    httpClient<ActionsControllerManageYieldResponse>(getActionsControllerManageYieldUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(createManageActionDto),
    });

/**
 * Submit the transaction hash after broadcasting a transaction to the blockchain. This updates the transaction status and enables tracking.
 * @summary Submit transaction hash
 */
export type TransactionsControllerSubmitTransactionHashResponse200 = {
    data: TransactionDto;
    status: 200;
};

export type TransactionsControllerSubmitTransactionHashResponse400 = {
    data: void;
    status: 400;
};

export type TransactionsControllerSubmitTransactionHashResponse401 = {
    data: TransactionsControllerSubmitTransactionHash401;
    status: 401;
};

export type TransactionsControllerSubmitTransactionHashResponse404 = {
    data: void;
    status: 404;
};

export type TransactionsControllerSubmitTransactionHashResponse429 = {
    data: TransactionsControllerSubmitTransactionHash429;
    status: 429;
};

export type TransactionsControllerSubmitTransactionHashResponse500 = {
    data: TransactionsControllerSubmitTransactionHash500;
    status: 500;
};

export type TransactionsControllerSubmitTransactionHashResponseSuccess =
    TransactionsControllerSubmitTransactionHashResponse200 & {
        headers: Headers;
    };
export type TransactionsControllerSubmitTransactionHashResponseError = (
    | TransactionsControllerSubmitTransactionHashResponse400
    | TransactionsControllerSubmitTransactionHashResponse401
    | TransactionsControllerSubmitTransactionHashResponse404
    | TransactionsControllerSubmitTransactionHashResponse429
    | TransactionsControllerSubmitTransactionHashResponse500
) & {
    headers: Headers;
};

export type TransactionsControllerSubmitTransactionHashResponse =
    | TransactionsControllerSubmitTransactionHashResponseSuccess
    | TransactionsControllerSubmitTransactionHashResponseError;

export const getTransactionsControllerSubmitTransactionHashUrl = ({
    transactionId,
}: TransactionsControllerSubmitTransactionHashPathParameters) =>
    `/v1/transactions/${transactionId}/submit-hash`;

export const transactionsControllerSubmitTransactionHash = (
    { transactionId }: TransactionsControllerSubmitTransactionHashPathParameters,
    submitHashDto: SubmitHashDto,
    options?: RequestInit,
): Promise<TransactionsControllerSubmitTransactionHashResponse> =>
    httpClient<TransactionsControllerSubmitTransactionHashResponse>(
        getTransactionsControllerSubmitTransactionHashUrl({ transactionId }),
        {
            ...options,
            method: 'PUT',
            headers: { 'Content-Type': 'application/json', ...options?.headers },
            body: JSON.stringify(submitHashDto),
        },
    );

/**
 * Submit the transaction to the blockchain.
 * @summary Submit transaction
 */
export type TransactionsControllerSubmitTransactionResponse200 = {
    data: TransactionDto;
    status: 200;
};

export type TransactionsControllerSubmitTransactionResponse400 = {
    data: void;
    status: 400;
};

export type TransactionsControllerSubmitTransactionResponse401 = {
    data: TransactionsControllerSubmitTransaction401;
    status: 401;
};

export type TransactionsControllerSubmitTransactionResponse404 = {
    data: void;
    status: 404;
};

export type TransactionsControllerSubmitTransactionResponse429 = {
    data: TransactionsControllerSubmitTransaction429;
    status: 429;
};

export type TransactionsControllerSubmitTransactionResponse500 = {
    data: TransactionsControllerSubmitTransaction500;
    status: 500;
};

export type TransactionsControllerSubmitTransactionResponseSuccess =
    TransactionsControllerSubmitTransactionResponse200 & {
        headers: Headers;
    };
export type TransactionsControllerSubmitTransactionResponseError = (
    | TransactionsControllerSubmitTransactionResponse400
    | TransactionsControllerSubmitTransactionResponse401
    | TransactionsControllerSubmitTransactionResponse404
    | TransactionsControllerSubmitTransactionResponse429
    | TransactionsControllerSubmitTransactionResponse500
) & {
    headers: Headers;
};

export type TransactionsControllerSubmitTransactionResponse =
    | TransactionsControllerSubmitTransactionResponseSuccess
    | TransactionsControllerSubmitTransactionResponseError;

export const getTransactionsControllerSubmitTransactionUrl = ({
    transactionId,
}: TransactionsControllerSubmitTransactionPathParameters) =>
    `/v1/transactions/${transactionId}/submit`;

export const transactionsControllerSubmitTransaction = (
    { transactionId }: TransactionsControllerSubmitTransactionPathParameters,
    submitTransactionDto: SubmitTransactionDto,
    options?: RequestInit,
): Promise<TransactionsControllerSubmitTransactionResponse> =>
    httpClient<TransactionsControllerSubmitTransactionResponse>(
        getTransactionsControllerSubmitTransactionUrl({ transactionId }),
        {
            ...options,
            method: 'POST',
            headers: { 'Content-Type': 'application/json', ...options?.headers },
            body: JSON.stringify(submitTransactionDto),
        },
    );

/**
 * Retrieve detailed information about a specific transaction including current status, hash, and execution details.
 * @summary Get transaction details
 */
export type TransactionsControllerGetTransactionResponse200 = {
    data: TransactionDto;
    status: 200;
};

export type TransactionsControllerGetTransactionResponse400 = {
    data: TransactionsControllerGetTransaction400;
    status: 400;
};

export type TransactionsControllerGetTransactionResponse401 = {
    data: TransactionsControllerGetTransaction401;
    status: 401;
};

export type TransactionsControllerGetTransactionResponse404 = {
    data: void;
    status: 404;
};

export type TransactionsControllerGetTransactionResponse429 = {
    data: TransactionsControllerGetTransaction429;
    status: 429;
};

export type TransactionsControllerGetTransactionResponse500 = {
    data: TransactionsControllerGetTransaction500;
    status: 500;
};

export type TransactionsControllerGetTransactionResponseSuccess =
    TransactionsControllerGetTransactionResponse200 & {
        headers: Headers;
    };
export type TransactionsControllerGetTransactionResponseError = (
    | TransactionsControllerGetTransactionResponse400
    | TransactionsControllerGetTransactionResponse401
    | TransactionsControllerGetTransactionResponse404
    | TransactionsControllerGetTransactionResponse429
    | TransactionsControllerGetTransactionResponse500
) & {
    headers: Headers;
};

export type TransactionsControllerGetTransactionResponse =
    | TransactionsControllerGetTransactionResponseSuccess
    | TransactionsControllerGetTransactionResponseError;

export const getTransactionsControllerGetTransactionUrl = ({
    transactionId,
}: TransactionsControllerGetTransactionPathParameters) => `/v1/transactions/${transactionId}`;

export const transactionsControllerGetTransaction = (
    { transactionId }: TransactionsControllerGetTransactionPathParameters,
    options?: RequestInit,
): Promise<TransactionsControllerGetTransactionResponse> =>
    httpClient<TransactionsControllerGetTransactionResponse>(
        getTransactionsControllerGetTransactionUrl({ transactionId }),
        {
            ...options,
            method: 'GET',
        },
    );
