/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Yield.xyz API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type {
    NetworkDto,
    NetworksControllerGetNetworks400,
    NetworksControllerGetNetworks401,
    NetworksControllerGetNetworks429,
    NetworksControllerGetNetworks500,
    ProviderDto,
    ProvidersControllerGetProvider400,
    ProvidersControllerGetProvider401,
    ProvidersControllerGetProvider429,
    ProvidersControllerGetProvider500,
    ProvidersControllerGetProviderPathParameters,
    ProvidersControllerGetProviders200,
    ProvidersControllerGetProviders400,
    ProvidersControllerGetProviders401,
    ProvidersControllerGetProviders429,
    ProvidersControllerGetProviders500,
    ProvidersControllerGetProvidersParams,
    YieldDto,
    YieldsControllerGetYield400,
    YieldsControllerGetYield401,
    YieldsControllerGetYield429,
    YieldsControllerGetYield500,
    YieldsControllerGetYieldPathParameters,
    YieldsControllerGetYieldValidators200,
    YieldsControllerGetYieldValidators400,
    YieldsControllerGetYieldValidators401,
    YieldsControllerGetYieldValidators429,
    YieldsControllerGetYieldValidators500,
    YieldsControllerGetYieldValidatorsParams,
    YieldsControllerGetYieldValidatorsPathParameters,
    YieldsControllerGetYields200,
    YieldsControllerGetYields400,
    YieldsControllerGetYields401,
    YieldsControllerGetYields429,
    YieldsControllerGetYields500,
    YieldsControllerGetYieldsParams,
} from './index.schemas';
import { httpClient } from '../httpClient';

/**
 * Retrieve a paginated list of available yield opportunities across all supported networks and protocols.
 * @summary List all yield opportunities
 */
export type YieldsControllerGetYieldsResponse200 = {
    data: YieldsControllerGetYields200;
    status: 200;
};

export type YieldsControllerGetYieldsResponse400 = {
    data: YieldsControllerGetYields400;
    status: 400;
};

export type YieldsControllerGetYieldsResponse401 = {
    data: YieldsControllerGetYields401;
    status: 401;
};

export type YieldsControllerGetYieldsResponse429 = {
    data: YieldsControllerGetYields429;
    status: 429;
};

export type YieldsControllerGetYieldsResponse500 = {
    data: YieldsControllerGetYields500;
    status: 500;
};

export type YieldsControllerGetYieldsResponseSuccess = YieldsControllerGetYieldsResponse200 & {
    headers: Headers;
};
export type YieldsControllerGetYieldsResponseError = (
    | YieldsControllerGetYieldsResponse400
    | YieldsControllerGetYieldsResponse401
    | YieldsControllerGetYieldsResponse429
    | YieldsControllerGetYieldsResponse500
) & {
    headers: Headers;
};

export type YieldsControllerGetYieldsResponse =
    | YieldsControllerGetYieldsResponseSuccess
    | YieldsControllerGetYieldsResponseError;

export const getYieldsControllerGetYieldsUrl = (params?: YieldsControllerGetYieldsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/v1/yields?${stringifiedParams}` : `/v1/yields`;
};

export const yieldsControllerGetYields = (
    params?: YieldsControllerGetYieldsParams,
    options?: RequestInit,
): Promise<YieldsControllerGetYieldsResponse> =>
    httpClient<YieldsControllerGetYieldsResponse>(getYieldsControllerGetYieldsUrl(params), {
        ...options,
        method: 'GET',
    });

/**
 * Retrieve detailed information about a specific yield opportunity including APY, tokens, protocol details, and more.
 * @summary Get yield metadata
 */
export type YieldsControllerGetYieldResponse200 = {
    data: YieldDto;
    status: 200;
};

export type YieldsControllerGetYieldResponse400 = {
    data: YieldsControllerGetYield400;
    status: 400;
};

export type YieldsControllerGetYieldResponse401 = {
    data: YieldsControllerGetYield401;
    status: 401;
};

export type YieldsControllerGetYieldResponse404 = {
    data: void;
    status: 404;
};

export type YieldsControllerGetYieldResponse429 = {
    data: YieldsControllerGetYield429;
    status: 429;
};

export type YieldsControllerGetYieldResponse500 = {
    data: YieldsControllerGetYield500;
    status: 500;
};

export type YieldsControllerGetYieldResponseSuccess = YieldsControllerGetYieldResponse200 & {
    headers: Headers;
};
export type YieldsControllerGetYieldResponseError = (
    | YieldsControllerGetYieldResponse400
    | YieldsControllerGetYieldResponse401
    | YieldsControllerGetYieldResponse404
    | YieldsControllerGetYieldResponse429
    | YieldsControllerGetYieldResponse500
) & {
    headers: Headers;
};

export type YieldsControllerGetYieldResponse =
    | YieldsControllerGetYieldResponseSuccess
    | YieldsControllerGetYieldResponseError;

export const getYieldsControllerGetYieldUrl = ({
    yieldId,
}: YieldsControllerGetYieldPathParameters) => `/v1/yields/${yieldId}`;

export const yieldsControllerGetYield = (
    { yieldId }: YieldsControllerGetYieldPathParameters,
    options?: RequestInit,
): Promise<YieldsControllerGetYieldResponse> =>
    httpClient<YieldsControllerGetYieldResponse>(getYieldsControllerGetYieldUrl({ yieldId }), {
        ...options,
        method: 'GET',
    });

/**
 * Retrieve a paginated list of validators available for staking or delegation for this yield opportunity.
 * @summary Get yield validators
 */
export type YieldsControllerGetYieldValidatorsResponse200 = {
    data: YieldsControllerGetYieldValidators200;
    status: 200;
};

export type YieldsControllerGetYieldValidatorsResponse400 = {
    data: YieldsControllerGetYieldValidators400;
    status: 400;
};

export type YieldsControllerGetYieldValidatorsResponse401 = {
    data: YieldsControllerGetYieldValidators401;
    status: 401;
};

export type YieldsControllerGetYieldValidatorsResponse404 = {
    data: void;
    status: 404;
};

export type YieldsControllerGetYieldValidatorsResponse429 = {
    data: YieldsControllerGetYieldValidators429;
    status: 429;
};

export type YieldsControllerGetYieldValidatorsResponse500 = {
    data: YieldsControllerGetYieldValidators500;
    status: 500;
};

export type YieldsControllerGetYieldValidatorsResponseSuccess =
    YieldsControllerGetYieldValidatorsResponse200 & {
        headers: Headers;
    };
export type YieldsControllerGetYieldValidatorsResponseError = (
    | YieldsControllerGetYieldValidatorsResponse400
    | YieldsControllerGetYieldValidatorsResponse401
    | YieldsControllerGetYieldValidatorsResponse404
    | YieldsControllerGetYieldValidatorsResponse429
    | YieldsControllerGetYieldValidatorsResponse500
) & {
    headers: Headers;
};

export type YieldsControllerGetYieldValidatorsResponse =
    | YieldsControllerGetYieldValidatorsResponseSuccess
    | YieldsControllerGetYieldValidatorsResponseError;

export const getYieldsControllerGetYieldValidatorsUrl = (
    { yieldId }: YieldsControllerGetYieldValidatorsPathParameters,
    params?: YieldsControllerGetYieldValidatorsParams,
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/v1/yields/${yieldId}/validators?${stringifiedParams}`
        : `/v1/yields/${yieldId}/validators`;
};

export const yieldsControllerGetYieldValidators = (
    { yieldId }: YieldsControllerGetYieldValidatorsPathParameters,
    params?: YieldsControllerGetYieldValidatorsParams,
    options?: RequestInit,
): Promise<YieldsControllerGetYieldValidatorsResponse> =>
    httpClient<YieldsControllerGetYieldValidatorsResponse>(
        getYieldsControllerGetYieldValidatorsUrl({ yieldId }, params),
        {
            ...options,
            method: 'GET',
        },
    );

/**
 * Retrieve a list of all supported networks that can be used for filtering yields and other operations.
 * @summary List all available networks
 */
export type NetworksControllerGetNetworksResponse200 = {
    data: NetworkDto[];
    status: 200;
};

export type NetworksControllerGetNetworksResponse400 = {
    data: NetworksControllerGetNetworks400;
    status: 400;
};

export type NetworksControllerGetNetworksResponse401 = {
    data: NetworksControllerGetNetworks401;
    status: 401;
};

export type NetworksControllerGetNetworksResponse429 = {
    data: NetworksControllerGetNetworks429;
    status: 429;
};

export type NetworksControllerGetNetworksResponse500 = {
    data: NetworksControllerGetNetworks500;
    status: 500;
};

export type NetworksControllerGetNetworksResponseSuccess =
    NetworksControllerGetNetworksResponse200 & {
        headers: Headers;
    };
export type NetworksControllerGetNetworksResponseError = (
    | NetworksControllerGetNetworksResponse400
    | NetworksControllerGetNetworksResponse401
    | NetworksControllerGetNetworksResponse429
    | NetworksControllerGetNetworksResponse500
) & {
    headers: Headers;
};

export type NetworksControllerGetNetworksResponse =
    | NetworksControllerGetNetworksResponseSuccess
    | NetworksControllerGetNetworksResponseError;

export const getNetworksControllerGetNetworksUrl = () => `/v1/networks`;

export const networksControllerGetNetworks = (
    options?: RequestInit,
): Promise<NetworksControllerGetNetworksResponse> =>
    httpClient<NetworksControllerGetNetworksResponse>(getNetworksControllerGetNetworksUrl(), {
        ...options,
        method: 'GET',
    });

/**
 * Returns a paginated list of all providers, including both protocol and validator providers.
 * @summary Get all providers
 */
export type ProvidersControllerGetProvidersResponse200 = {
    data: ProvidersControllerGetProviders200;
    status: 200;
};

export type ProvidersControllerGetProvidersResponse400 = {
    data: ProvidersControllerGetProviders400;
    status: 400;
};

export type ProvidersControllerGetProvidersResponse401 = {
    data: ProvidersControllerGetProviders401;
    status: 401;
};

export type ProvidersControllerGetProvidersResponse429 = {
    data: ProvidersControllerGetProviders429;
    status: 429;
};

export type ProvidersControllerGetProvidersResponse500 = {
    data: ProvidersControllerGetProviders500;
    status: 500;
};

export type ProvidersControllerGetProvidersResponseSuccess =
    ProvidersControllerGetProvidersResponse200 & {
        headers: Headers;
    };
export type ProvidersControllerGetProvidersResponseError = (
    | ProvidersControllerGetProvidersResponse400
    | ProvidersControllerGetProvidersResponse401
    | ProvidersControllerGetProvidersResponse429
    | ProvidersControllerGetProvidersResponse500
) & {
    headers: Headers;
};

export type ProvidersControllerGetProvidersResponse =
    | ProvidersControllerGetProvidersResponseSuccess
    | ProvidersControllerGetProvidersResponseError;

export const getProvidersControllerGetProvidersUrl = (
    params?: ProvidersControllerGetProvidersParams,
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/v1/providers?${stringifiedParams}` : `/v1/providers`;
};

export const providersControllerGetProviders = (
    params?: ProvidersControllerGetProvidersParams,
    options?: RequestInit,
): Promise<ProvidersControllerGetProvidersResponse> =>
    httpClient<ProvidersControllerGetProvidersResponse>(
        getProvidersControllerGetProvidersUrl(params),
        {
            ...options,
            method: 'GET',
        },
    );

/**
 * Returns detailed information about a specific provider.
 * @summary Get provider by ID
 */
export type ProvidersControllerGetProviderResponse200 = {
    data: ProviderDto;
    status: 200;
};

export type ProvidersControllerGetProviderResponse400 = {
    data: ProvidersControllerGetProvider400;
    status: 400;
};

export type ProvidersControllerGetProviderResponse401 = {
    data: ProvidersControllerGetProvider401;
    status: 401;
};

export type ProvidersControllerGetProviderResponse429 = {
    data: ProvidersControllerGetProvider429;
    status: 429;
};

export type ProvidersControllerGetProviderResponse500 = {
    data: ProvidersControllerGetProvider500;
    status: 500;
};

export type ProvidersControllerGetProviderResponseSuccess =
    ProvidersControllerGetProviderResponse200 & {
        headers: Headers;
    };
export type ProvidersControllerGetProviderResponseError = (
    | ProvidersControllerGetProviderResponse400
    | ProvidersControllerGetProviderResponse401
    | ProvidersControllerGetProviderResponse429
    | ProvidersControllerGetProviderResponse500
) & {
    headers: Headers;
};

export type ProvidersControllerGetProviderResponse =
    | ProvidersControllerGetProviderResponseSuccess
    | ProvidersControllerGetProviderResponseError;

export const getProvidersControllerGetProviderUrl = ({
    providerId,
}: ProvidersControllerGetProviderPathParameters) => `/v1/providers/${providerId}`;

export const providersControllerGetProvider = (
    { providerId }: ProvidersControllerGetProviderPathParameters,
    options?: RequestInit,
): Promise<ProvidersControllerGetProviderResponse> =>
    httpClient<ProvidersControllerGetProviderResponse>(
        getProvidersControllerGetProviderUrl({ providerId }),
        {
            ...options,
            method: 'GET',
        },
    );
