/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Yield.xyz API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { HealthStatusDto } from './index.schemas';
import { httpClient } from '../httpClient';

/**
 * Get the health status of the yield API with current timestamp
 * @summary Health check
 */
export type HealthControllerHealthResponse200 = {
    data: HealthStatusDto;
    status: 200;
};

export type HealthControllerHealthResponseSuccess = HealthControllerHealthResponse200 & {
    headers: Headers;
};
export type HealthControllerHealthResponse = HealthControllerHealthResponseSuccess;

export const getHealthControllerHealthUrl = () => `/health`;

export const healthControllerHealth = (
    options?: RequestInit,
): Promise<HealthControllerHealthResponse> =>
    httpClient<HealthControllerHealthResponse>(getHealthControllerHealthUrl(), {
        ...options,
        method: 'GET',
    });
