/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Yield.xyz API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type {
    BalancesRequestDto,
    BalancesResponseDto,
    YieldBalancesDto,
    YieldBalancesRequestDto,
    YieldsControllerGetAggregateBalances400,
    YieldsControllerGetAggregateBalances401,
    YieldsControllerGetAggregateBalances429,
    YieldsControllerGetAggregateBalances500,
    YieldsControllerGetYieldBalances400,
    YieldsControllerGetYieldBalances401,
    YieldsControllerGetYieldBalances429,
    YieldsControllerGetYieldBalances500,
    YieldsControllerGetYieldBalancesPathParameters,
} from './index.schemas';
import { httpClient } from '../httpClient';

/**
 * Retrieve balances for multiple wallet addresses across different networks and yield opportunities. Send an array of balance requests - each request can specify a yieldId (optional for chain scanning), address, network, and custom arguments. This is the same format as the single yield balance endpoint but in array form. Duplicate requests (same yieldId + address + network) are automatically deduplicated, with specific yield requests taking precedence over chain scans.
 * @summary Get balances across multiple yields and networks
 */
export type YieldsControllerGetAggregateBalancesResponse200 = {
    data: BalancesResponseDto;
    status: 200;
};

export type YieldsControllerGetAggregateBalancesResponse400 = {
    data: YieldsControllerGetAggregateBalances400;
    status: 400;
};

export type YieldsControllerGetAggregateBalancesResponse401 = {
    data: YieldsControllerGetAggregateBalances401;
    status: 401;
};

export type YieldsControllerGetAggregateBalancesResponse429 = {
    data: YieldsControllerGetAggregateBalances429;
    status: 429;
};

export type YieldsControllerGetAggregateBalancesResponse500 = {
    data: YieldsControllerGetAggregateBalances500;
    status: 500;
};

export type YieldsControllerGetAggregateBalancesResponseSuccess =
    YieldsControllerGetAggregateBalancesResponse200 & {
        headers: Headers;
    };
export type YieldsControllerGetAggregateBalancesResponseError = (
    | YieldsControllerGetAggregateBalancesResponse400
    | YieldsControllerGetAggregateBalancesResponse401
    | YieldsControllerGetAggregateBalancesResponse429
    | YieldsControllerGetAggregateBalancesResponse500
) & {
    headers: Headers;
};

export type YieldsControllerGetAggregateBalancesResponse =
    | YieldsControllerGetAggregateBalancesResponseSuccess
    | YieldsControllerGetAggregateBalancesResponseError;

export const getYieldsControllerGetAggregateBalancesUrl = () => `/v1/yields/balances`;

export const yieldsControllerGetAggregateBalances = (
    balancesRequestDto: BalancesRequestDto,
    options?: RequestInit,
): Promise<YieldsControllerGetAggregateBalancesResponse> =>
    httpClient<YieldsControllerGetAggregateBalancesResponse>(
        getYieldsControllerGetAggregateBalancesUrl(),
        {
            ...options,
            method: 'POST',
            headers: { 'Content-Type': 'application/json', ...options?.headers },
            body: JSON.stringify(balancesRequestDto),
        },
    );

/**
 * Retrieve all balances associated with a yield opportunity for a specific wallet address, including active, pending, claimable, and withdrawable balances. The network is automatically determined from the yield configuration.
 * @summary Get balances for a specific yield
 */
export type YieldsControllerGetYieldBalancesResponse200 = {
    data: YieldBalancesDto;
    status: 200;
};

export type YieldsControllerGetYieldBalancesResponse400 = {
    data: YieldsControllerGetYieldBalances400;
    status: 400;
};

export type YieldsControllerGetYieldBalancesResponse401 = {
    data: YieldsControllerGetYieldBalances401;
    status: 401;
};

export type YieldsControllerGetYieldBalancesResponse404 = {
    data: void;
    status: 404;
};

export type YieldsControllerGetYieldBalancesResponse429 = {
    data: YieldsControllerGetYieldBalances429;
    status: 429;
};

export type YieldsControllerGetYieldBalancesResponse500 = {
    data: YieldsControllerGetYieldBalances500;
    status: 500;
};

export type YieldsControllerGetYieldBalancesResponseSuccess =
    YieldsControllerGetYieldBalancesResponse200 & {
        headers: Headers;
    };
export type YieldsControllerGetYieldBalancesResponseError = (
    | YieldsControllerGetYieldBalancesResponse400
    | YieldsControllerGetYieldBalancesResponse401
    | YieldsControllerGetYieldBalancesResponse404
    | YieldsControllerGetYieldBalancesResponse429
    | YieldsControllerGetYieldBalancesResponse500
) & {
    headers: Headers;
};

export type YieldsControllerGetYieldBalancesResponse =
    | YieldsControllerGetYieldBalancesResponseSuccess
    | YieldsControllerGetYieldBalancesResponseError;

export const getYieldsControllerGetYieldBalancesUrl = ({
    yieldId,
}: YieldsControllerGetYieldBalancesPathParameters) => `/v1/yields/${yieldId}/balances`;

export const yieldsControllerGetYieldBalances = (
    { yieldId }: YieldsControllerGetYieldBalancesPathParameters,
    yieldBalancesRequestDto: YieldBalancesRequestDto,
    options?: RequestInit,
): Promise<YieldsControllerGetYieldBalancesResponse> =>
    httpClient<YieldsControllerGetYieldBalancesResponse>(
        getYieldsControllerGetYieldBalancesUrl({ yieldId }),
        {
            ...options,
            method: 'POST',
            headers: { 'Content-Type': 'application/json', ...options?.headers },
            body: JSON.stringify(yieldBalancesRequestDto),
        },
    );
