name: "[Test] Nightly Suite Desktop e2e Windows tests"
# Nightly scheduled check on develop branch
# Builds the desktop app
# Runs full e2e test suite for Suite Desktop

on:
#   schedule:
#     - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # build-app:
  #   if: github.repository == 'trezor/trezor-suite'
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
  #     - name: Build and Upload Suite Desktop
  #       uses: ./.github/actions/build-desktop
  
  run-e2e-suite-desktop-tests:
    if: github.repository == 'trezor/trezor-suite'
    runs-on: windows-latest
    # needs:
    #   - build-app
    steps:
      - name: Hello
        run: echo "Hello World!"