name: "[Test] suite-native Android E2E"

permissions:
  id-token: write # for fetching the OIDC token (needed for aws s3 actions)

on:
  # schedule:
  #   - cron: "0 0 * * *"
  # pull_request:
  #   paths:
  #     - "suite-native/**"
  #     - "suite-common/**"
  #     - "packages/connect/**"
  #     - ".github/workflows/test-suite-native-e2e-android.yml"
  #     - "!**.md"
  # push:
  #   branches:
  #     - release-native/*
  workflow_dispatch:
    inputs:
      publishResultsToGitHub:
        description: "(optional) Publish test report to GitHub Project"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: "test"
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  RN_SRC_EXT: "e2e.ts,e2e.tsx"

jobs:
  run_android_e2e_tests:
    uses: ./.github/workflows/job-template-android-e2e.yml
    with:
      emulator_model: "T3W1"
      detox_extra_args: "--testNamePattern '^(?!.*@specificModel)'"
